services: 
  my-todo-list-api:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports: 
      - 5000:5000
    container_name: MyTodoListDev
    volumes:
      - .:/app
    environment:
      - DOTNET_WATCH_RESTART_ON_RUDE_EDIT=1
    command: dotnet watch