services: 
  my-todo-list-api:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports: 
      - 5000:5000
    container_name: MyTodoListDev
    volumes:
      - .:/app
    command: dotnet watch